services:
  db:
    image: postgres:14.1
    container_name: compose_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend/flightsapp/
    container_name: compose_frontend
    ports: 
      - "4173:4173"
    networks:
      - app_network

  backend:
    build:
      context: ./backend/flightsapp/
    container_name: compose_backend
    ports:
      - "8080:8080"
    depends_on:
      - externalapi
      - db
    networks:
      - app_network

  externalapi:
    build:
      context: ./external_api/
    container_name: compose_external_api
    ports:
      - "3000:3000"
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx/
    container_name: compose_nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - externalapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
